TrajectoryPlannerROS:
  max_vel_x: .8
  min_vel_x: 0.1
  max_rotational_vel: .1
  min_in_place_rotational_vel: .25
  min_in_place_vel_theta: .25
  max_vel_theta: 1.5
  min_vel_theta: -1.5
  backup_vel : -.2
  acc_lim_th: 3.4
  acc_lim_x: 2.6
  acc_lim_y: 0
  holonomic_robot: false
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.05