obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.117, -0.1], [-0.117, 0.1], [0.117, 0.1], [0.117, -0.1]]

inflation_radius: 0.3
map_topic : /map
map_type : costmap
inflation_radius: .75
cost_scaling_factor: 10.0
observation_sources: scan
scan: {sensor_frame: lidar_1, observation_persistence: 0.0, max_obstacle_height: 0.6, 
      min_obstacle_height: 0.0, data_type: LaserScan, topic: /scan, marking: true, clearing: true}